---
sidebar: sidebar
permalink: reference-log-in-to-instance.html
keywords: log in, data sense, classification
summary: At times you may need to log into the NetApp Data Classification system so you can access log files or edit configuration files.
---
= Log in to the NetApp Data Classification system
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You need to log into NetApp Data Classification system so you can access log files or edit configuration files.

When Data Classification is installed on a Linux machine on your premises, or on a Linux machine you deployed in the cloud, you can access the configuration file and script directly.

When Data Classification is deployed in the cloud, you need to SSH to the Data Classification instance. You SSH to the system by entering the user and password, or by using the SSH key you provided during the Console agent installation. The SSH command is:

`ssh -i <path_to_the_ssh_key> <machine_user>@<datasense_ip>`


* `<path_to_the_ssh_key>` = location of ssh authentication keys
* `<machine_user>:`
** For AWS: use the <ec2-user>
** For Azure: use the user created for the Console instance
** For GCP: use the user created for the Console instance
* `<datasense_ip>` = IP address of the virtual machine instance

You need to modify the security group inbound rules to access the system in the cloud. For details, see: 

* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-aws.html[Security group rules in AWS^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html[Security group rules in Azure^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-gcp.html[Firewall rules in Google Cloud^]
