---
sidebar: sidebar
permalink: task-deploy-overview.html
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification
summary: Plan which deployment of NetApp Data Classification meets your needs.
---
= NetApp Data Classification deployment methods
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Data Classification supports several deployment methods for different network and connectivity requirements. Review the available methods to choose the option that best fits your environment.

* link:task-deploy-cloud-compliance.html[Deploy in the cloud using the Console]. The Console deploys the Data Classification instance in the same cloud provider network as the Console agent.
* link:task-deploy-compliance-onprem.html[Install on a Linux host with internet access]. Install Data Classification on a Linux host in your network or in the cloud. This option might be useful if you prefer to scan on-premises ONTAP systems from a Data Classification instance located on premises, but locating the instance on premises is not required.
* link:task-deploy-compliance-dark-site.html[Install on a Linux host in an on-premises site without internet access], called _private mode._ This type of installation, which uses an installation script, has no connectivity to the Console SaaS layer. 

include::_include/ova-deployment.adoc[]

== On-premises installation script

Both installation methods use an installation script. The script checks whether the system and environment meet the prerequisites. If they do, installation starts.

A separate software package is available to verify whether your Linux host is ready. To run the verification package, see link:task-test-linux-system.html[verify your Linux host is ready to install Data Classification].
