=== Version 1.44

This BlueXP classification release includes:

.Improved update times for the Governance dashboard 

Update times for individual components of the Governance dashboard have been improved. The following table displays the frequency of updates for each component.   

[cols="1,1", options="header"]
|===
|Component |Update times

|Age of Data |24 hours
|Categories |24 hours
|Data Overview |5 minutes
|Duplicate Files |2 hours
|File Types |24 hours
|Non-Business Data |2 hours
|Open Permissions |24 hours
|Saved Searches |2 hours
|Sensitive Data and Wide Permissions |24 hours
|Size of Data |24 hours
|Stale Data |2 hours
|Top Data Repositories by Sensitivity Level |2 hours
|===

You can view the time of the last update and manually update the Duplicate Files, Non-Business Data, Saved Searches, Stale Data, and Top Data Repositories by Sensitivity Level components. For more information about the Governance dashboard, see link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html[View governance details about the data stored in your organization]. 

.Performance and security improvements 

Enhancements have been made to improve BlueXP classification's performance, memory consumption, and security. 

.Bug fixes 

Redis has been upgraded to improve the reliability of BlueXP classification. BlueXP classification now uses Elasticsearch to improve the accuracy of file count reporting during scans. 
