=== Version 1.47

.BlueXP classification is now NetApp Data Classification

BlueXP classification has been renamed NetApp Data Classification. In addition to the rename, the user interface has been enhanced. 

.BlueXP is now NetApp Console

BlueXP has been renamed and redesigned to better reflect its role in managing your data infrastructure.  
 
The NetApp Console provides centralized management of storage and data services across on-premises and cloud environments at enterprise grade—delivering real-time insights, faster workflows, and simplified administration.
 
For details on what has changed, see the https://docs.netapp.com/us-en/bluexp-relnotes/index.html[NetApp Console release notes].

.Policies (preview)

Saved searches have been renamed saved queries. You can also turn saved queries into actionable policies: delete dat or send email notifications based on saved query results. 

To learn more, see link:task-using-policies.html[Create policies].

.Actions (preview)

Data Classification now supports actions in the __ page. You can copy, move, and delete files from Data Classification.

.Tagging (preview)

Add tags to workloads. 
