=== Version 1.39
This BlueXP classification release updates the export process for the Data Investigation report. This export update is useful for performing additional analyses on your data, creating additional visualizations on the data, or sharing the results of your data investigation with others.

Previously, the Data Investigation report export was limited to 10,000 rows. With this release, the limit has been removed so that you can export all of your data. This change enables you to export more data from your Data Investigation reports, providing you with more flexibility in your data analysis.

You can choose the working environment, volumes, destination folder, and either JSON or CSV format. The exported filename includes a timestamp to help you identify when the data was exported.

The supported working environments include: 

* Cloud Volumes ONTAP 
* FSx for ONTAP
* ONTAP
* Share group   

Exporting data from the Data Investigation report has the following limitations: 

* The maximum number of records to download is 500 million. per type (files, directories, and tables)
* One million records are expected to take about 35 minutes to export.
 

For details about data investigation and the report, see https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html[Investigate data stored in your organization].

//For details about data investigation and the report, see link:../task-investigate-data.html[Investigate data stored in your organization].