=== Version 1.50

This release of Data Classification includes bug fixes and the following updates:

.Custom classification improvements

Data Classification now supports creating custom categorings for your data. You can upload files to finetune an AI model that Data Classification uses to apply the category marker to data. The interface for all custom classifications has been improved. 

For more information, see link:task-custom-classification.html[Create a custom classification].

//For more information, see link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html[Create a custom classification].

.Custom stale data 

Data Classification now allows you to customize the definition of stale data so it suits your organizational needs. Previously Stale data can be determined based on when it was last accessed _or_ last modified. For either category, you can assign a time period of between 6 months and 10 years.

For more information, see link:task-stale-data.html[Customize the stale data definition].

//For more information, see link:https://docs.netapp.com/us-en/data-services-data-classification/task-stale-data.htmlCustomize the stale data definition].


.Improved performance

Data Classification has shortened the loading time for all pages in Data Classification as well as the data mapping report and filters on the Investigation page. 

.Estimated time for investigation reports

When you donwload an investigation report, Data Classification now reports the estimated time for the download to complete.  