=== Version 1.50

This release of Data Classification includes bug fixes and the following updates:

.Activate Data Classification with Amazon FSxN for ONTAP directly from the NetApp Console canvas

You can now activate FSxN systems directly from the NetApp Console canvas, enabling you to more quickly launch Data Classification for your FSxN systems. 

For more information about using Data Classification with Amazon FSxN for ONTAP, see link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-fsx.html[Scan Amazon FSxN for ONTAP volumes]

.Increased export limit for investigating directories

When you're exporting an investigation report about directories from the Investigation dashboard, you can now include 1-,000 rows. This increase from the previous limit of 5,000 supports larger-scale investigations of data governance and compliance. 

For more information, see link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html[Investigate data^].

.Estimated completion time for custom classifier training

When you create a custom classifier, the UI now displays the estimated completion time for training, enabling greater clarity on the model readiness process. 

For more information, see link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification[Create a custom classification^].

.Increased limit for copy and move

When copying or moving files, you can now move files up to 250 MB, an increase from the previous limit of 50 MB, enhancing your management of data directly from Data Classification.

.Data Classification has improved the user experience to improve the display on low-resolution screens. 